name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g less

      - name: Build Pelican site
        run: make publish

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages || true
          git checkout -B gh-pages
          git reset --hard
          rm -rf ./*
          cp -r output/* .
          rm -rf output
          touch .nojekyll
          git add -A
          git commit -m "Deploy updated site" || echo "No changes to commit"
          git push -f origin gh-pages
